name: Windows

on:
  push:
    branches: [ "ZenBot" ]
  pull_request:
    branches: [ "ZenBot" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: SysBot.NET.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Execute unit tests
      run: dotnet test
      
    - name: Build application
      run: >
        dotnet publish SysBot.Pokemon.WinForms/SysBot.Pokemon.WinForms.csproj
        --configuration Release
        --runtime win-x64
        --self-contained false
        /p:PublishSingleFile=true
        /p:IncludeAllContentForSelfExtract=true
        /p:PublishTrimmed=false
        /p:DebugType=portable
        /p:OutputPath=bin\Release\net9.0-windows\

    - name: Upload Application
      uses: actions/upload-artifact@v4
      with:
        name: SysBot.Pokemon.WinForms
        path: SysBot.Pokemon.WinForms\bin\Release\net9.0-windows\publish\*.exe

    - name: Format version number
      id: version
      run: |
        $runNumber = "${{ github.run_number }}"
        $lastDigit = $runNumber.Substring($runNumber.Length - 1)
        $firstDigits = $runNumber.Substring(0, $runNumber.Length - 1)
        $formattedVersion = "$firstDigits.$lastDigit"
        echo "number=$formattedVersion" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/ZenBot'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v4.9.6
        name: Release v4.9.6
        draft: false
        prerelease: false
        files: SysBot.Pokemon.WinForms/bin/Release/net9.0-windows/publish/*.exe
        generate_release_notes: true
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         
